
name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  security-testing:

    runs-on: ubuntu-latest

    steps:

      # STEP 1
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # STEP 3
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # STEP 4
      - name: Create Reports Folder
        run: |
          mkdir -p reports

      # STEP 5
      - name: Run PyTest
        run: |
          pytest > reports/pytest-report.txt

      # STEP 6
      - name: Run Bandit Security Scan
        run: |
          bandit -r app/ -f json -o reports/bandit-report.json || true

      # STEP 7
      - name: Run Safety Dependency Scan
        run: |
          safety check > reports/safety-report.txt || true

      # STEP 8
      - name: Build Docker Image
        run: |
          docker build -t inventory-app .

      # STEP 9
      - name: Run Trivy Docker Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: inventory-app
          format: table
          output: reports/trivy-report.txt

      # STEP 10
      - name: Commit Reports to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add reports/

          git commit -m "Auto-update security reports" || echo "No changes"

          git push
